megalo_security_homepage:
    path:     /login
    defaults: { _controller: MegaloSecurityBundle:Default:index }
    
megalo_security_log_action:
    path:     /login_go
    defaults: { _controller: MegaloSecurityBundle:Default:loginGo }
    
megalo_security_attempt:
    path:     /attempt
    defaults: { _controller: MegaloSecurityBundle:Default:attempt }
    
megalo_security_login_fail:
    path:     /login/fail
    defaults: { _controller: MegaloSecurityBundle:Default:loginFail }
    
megalo_security_login_success:
    path:     /login/success
    defaults: { _controller: MegaloSecurityBundle:Default:loginSuccess }
    
megalo_security_redefine_pass_user:
    path:     /login/redefineByUser
    defaults: { _controller: MegaloSecurityBundle:Default:loginRedefineByUser }
    
megalo_security_redefine_pass_admin:
    path:     /login/redefineByAdmin
    defaults: { _controller: MegaloSecurityBundle:Default:loginRedefineByAdmin }
